name:                haskellDB
version:             0.1.0.0
github:              "https://github.com/Gio-R/haskellDB"
license:             BSD3
author:              "Giorgia Rondinini"
maintainer:          ""
copyright:           "2019 Giorgia Rondinini"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Gio-R/haskellDB#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- beam-core 
- beam-postgres
- bytestring
- configurator
- hvect
- mtl
- postgresql-libpq
- scientific
- Spock >= 0.11
- text
- time
- transformers
- utf8-string
- wai-middleware-static

library:
  source-dirs: src

executables:
  haskellDB-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellDB

tests:
  haskellDB-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellDB
